# Generated by Django 4.1.1 on 2022-09-14 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab5App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='addingBooks',
            new_name='addingNote',
        ),
    ]
